name: Deploy to Main

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  promote-to-staging:
    name: Promote dev → staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Push changes to staging
        run: |
          git fetch origin
          git checkout staging
          git merge --no-ff dev -m "Auto-merge dev → staging [skip ci]"
          git push origin staging
