name: Deploy to Main

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  promote-to-staging:
    name: Promote dev → staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to staging
        run: |
          git fetch origin
          git checkout staging
          git merge dev
          git push origin staging

  promote-to-main:
    name: Promote staging → main
    needs: promote-to-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to main
        run: |
          git fetch origin
          git checkout main
          git merge staging
          git push origin main
          git status
