name: Deploy to Main

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  promote-to-staging:
    name: Promote dev → staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to staging
        run: |
          git fetch origin
          git checkout staging
          git merge dev --allow-unrelated-histories -m "Auto-merge dev → staging [skip ci]"
          git push origin staging
