name: Deploy to Main

on:
  push:
    branches: ["dev"]

jobs:
  promote-to-staging:
    name: Promote dev -> staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Push changes to staging
        run: |
          git fetch origin
          git checkout staging
          git merge dev
          git push origin staging
